version: '3'
services:
  postgresql:
    image: 'postgres:14.3'
    command:
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_connections=yes"
      - "-c"
      - "log_disconnections=yes"
      - "-c"
      - "log_statement=all"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev'
      PGPORT: '5432'
    # volumes:
      # - './phar-backup.sql:/docker-entrypoint-initdb.d/phar-backup.sql'
      # - './pgdata:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    logging:
      options:
        max-size: '10m'
        max-file: '50'
    restart: 'always'

