version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'demo'
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.12-management
    ports:
      - 5672:5672
      - 15672:15672

