apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-test
spec:
  selector:
    matchLabels:
      app: kickstart-dev
  template:
    metadata:
      labels:
        app: kickstart-dev
    spec:
      serviceAccountName: gcp_project_name-dev
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.6
        args: 
          - "--structured-logs"
          - "gcp_project_id:asia-east1:gcp_project_name-dev"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
      - name: kickstart-dev
        image: asia.gcr.io/gcp_project_id/kickstart:latest
        imagePullPolicy: "Always"
        command: ["/app"]
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: kickstart-dev
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kickstart-dev
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: kickstart-dev
              key: database
        - name: DATABASE_HOST
          value: "127.0.0.1"
        - name: DATABASE_DIALECT
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_MAX_IDLE_CONNECTIONS
          value: "3"
        - name: DATABASE_MAX_OPEN_CONNECTIONS
          value: "10"
        - name: DATABASE_MAX_CONN_LIFETIME_MS
          value: "300000"
        - name: SERVER_SHUTDOWN_GRACE_PERIOD_MS
          value: "30000"
        - name: NEW_RELIC_LICENSE
          value: "f048ba484cb182a62349da13d9e4843e980fc1f4"
        - name: PRODUCTION_ENVIRONMENT
          value: "false"
        - name: SERVICE_NAME_AS_ROOT
          value: "false"
        - name: SERVER_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: SERVER_LISTEN_PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "8"
        - name: PROJECT_NAME
          value: "kickstart"
        - name: PROJECT_ID
          value: "gcp_project_id"
        - name: CDN_URL_PREFIX
          value: "https://cdn.gcp_project_name.tw"
        - name: GCS_BUCKET_NAME
          value: "gcp_project_name"
        - name: GIN_MODE
          value: "release"
