package api

import (
	_ "github.com/A-pen-app/kickstart/docs"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func addDocRoutes(root *gin.RouterGroup) {

	// add routes to API documents generated by swaggo
	swaggerHandler := ginSwagger.WrapHandler(swaggerFiles.Handler)
	root.GET("/docs/*any", gin.BasicAuth(gin.Accounts{
		"kickstart": "kickstart",
	}), swaggerHandler)
}
